site_name: ME3 Manager Help
site_description: Documentation and blog for Mod Engine 3 Manager (ME3 Manager)
site_url: https://example.com
repo_url: https://github.com/2Pz/me3-manager

theme:
  name: material
  logo: assets/images/logo.png
  favicon: assets/images/favicon.ico
  font:
    text: Inter
    code: JetBrains Mono
  palette:
    - scheme: slate
      primary: grey
      accent: cyan
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
    - scheme: default
      primary: grey
      accent: cyan
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
  features:
    - navigation.instant
    - navigation.sections
    - navigation.expand
    - navigation.tabs
    - navigation.top
    - navigation.footer
    - header.autohide
    - toc.integrate
    - content.code.copy
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.action.edit

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/2Pz/me3-manager
    - icon: fontawesome/solid/globe
      link: https://me3.help/
  generator: false

extra_css:
  - assets/stylesheets/extra.css

markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.tasklist:
      custom_checkbox: true

plugins:
  - search
  - blog:
      blog_dir: blog
      blog_toc: true
      categories: true
      post_excerpt: required
  - tags

nav:
  - Overview: index.md
  - User Guide:
      - Getting Started: user-guide/getting-started.md
      - Main Interface: user-guide/main-interface.md
      - Installing Mods: user-guide/installing-mods.md
      - Managing Mods: user-guide/managing-mods.md
      - Profiles: user-guide/profiles.md
      - Game Management: user-guide/game-management.md
      - Settings: user-guide/settings.md
      - Troubleshooting: user-guide/troubleshooting.md
  - Blog: blog/index.md


